### ISSUE TITLE
Suport rootfs targeting multiple devices

### ISSUE THREAD

**Issue by lumag** [linux-msm/hexagonrpc#4]
Current hexagonrpcd has support for a single device configuration (including socinfo, DSP shell, libraries and other files). However it is sensible to be able to support multiple targets using the same rootfs. For example meta-qcom generates a single image for a variety of Qualcomm boards, including but not limited to all Dragonboards and Robotic RBn boards). Likewise Linaro's Debian images also support a variety of boards. It is imparctical for generic-purpose distros to provide single-device conflicting packages.

Can we please shift back to the structure that was outlined at https://gitlab.com/flamingradian/sensh/-/issues/1#note_1419039704 ? I.e. move all the files under `/usr/share/qcom/soc/vendor/device/`, following the linux-firmware approach. This way we will have:

- `/usr/share/qcom/apq8096/Qualcomm/db820c`
- `/usr/share/qcom/sdm845/Thundercomm/db845c`
- `/usr/share/qcom/sm8250/Thundercomm/RB5`
- `/usr/share/qcom/qcm2290/Thundercomm/RB1` (or `.../qrb2210/...`)
- `/usr/share/qcom/qrb4210/Thundercomm/RB2`

If this sounds sensible we can take a look at implementing these changes.

**Comment by lumag** [comment]
@flamingradian We have pushed out the DSP binaries for Robotics RBx boards to the https://github.com/linux-msm/dsp-binaries repo. Each set of DSP binaries gets installed to a subdir.

**Comment by flamingradian** [comment]
This is done in postmarketOS with the `-R` command line argument, where the exact path is specified for each device.

Is this about automatically detecting the SoC, vendor, and device name?

**Comment by lumag** [comment]
No, it's more about the `README.md` defining paths right under the `/usr/share/qcom`.

**Comment by flamingradian** [comment]
Oh, we can definitely change the README to match the paths better. The list just shows the defaults because no one is going to know to use `-R` when first running hexagonrpcd.
